global:
  resolve_timeout: 5m

route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m

  # A default receiver
  receiver: "internal-critical"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "internal-critical"
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

    - receiver: "internal-warning"
      group_wait: 10s
      match_re:
        severity: warning
      continue: true

    - receiver: "public"
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

receivers:
  - name: "internal-warning"
    telegram_configs:
      - bot_token: "${{TELEGRAM_TOKEN}}}}"
        chat_id: -1001904637278
        parse_mode: ""
  - name: "internal-critical"
    opsgenie_configs:
      - api_key: "${{OPS_GENIE_API_KEY}}"
  - name: "public"
    telegram_configs:
      - bot_token: "${{TELEGRAM_TOKEN}}"
        chat_id: -1002060420752
        parse_mode: ""

# The directory from which notification templates are read.
templates:
  - "/etc/alertmanager/template/*.tmpl"
