global:
  smtp_smarthost: "${SMTP_HOST}"
  smtp_from: "${SMTP_FROM}"
  smtp_auth_username: "${SMTP_AUTH_USERNAME}"
  smtp_auth_password: "${SMTP_AUTH_PASSWORD}"
  smtp_require_tls: true

route:
  group_by: ["instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "email_configs"
receivers:
  - name: "email_configs"
    email_configs:
      - to: "${EMAIL_TO}"
        send_resolved: true
