groups:
  - name: Oracle
    rules:
      - alert: TimeSinceLastUpdateTooHigh
        expr: time_since_last_update_seconds > 1800
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Time since the last update is too high"
          description: "The time since the last update from {{ $labels.publisher }} has exceeded 1800 seconds."
      - alert: WrongPrice
        expr: price_deviation > 0.025
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Price deviation is too high"
          description: "The price deviation of {{ $labels.pair }} from {{ $labels.source }} has exceeded 2.5%."
      - alert: TooFewSources
        expr: num_sources < 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Too few sources"
          description: "The number of sources for {{ $labels.pair }} has fallen below 5."
      - alert: SourceDeviation
        expr: price_deviation_source > 0.02
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Source deviation is too high"
          description: "The source deviation of {{ $labels.pair }} from {{ $labels.source }} has exceeded 2%."
      - alert: IndexerDown
        expr: indexer_blocks_left > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Indexer is down"
          description: "The {{ $labels.network }} indexer for {{ $labels.type }} is lagging behind 10 blocks."
  - name: API
    rules:
      - alert: TimeSinceLastUpdateTooHigh
        expr: api_time_since_last_update > 1800
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Time since the last update is too high"
          description: "The time since the last update for {{ $labels.pair }} has exceeded 1800 seconds."
      - alert: WrongPrice
        expr: api_price_deviation > 0.025
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Price deviation is too high"
          description: "The price deviation of {{ $labels.pair }} from DefiLlama has exceeded 2.5%."
      - alert: TooFewSources
        expr: api_num_sources < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Too few sources"
          description: "The number of sources for {{ $labels.pair }} has fallen below 1."
      - alert: SequencerDeviation
        expr: api_sequencer_deviation > 0.02
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Sequencer deviation is too high"
          description: "The ETH/STRK price has deviated from the sequencer price by more than 2%."
